name: gpaw
spack:
  commit: releases/v0.23
  repo: https://github.com/spack/spack.git
store: /user-environment
description: GPAW is a density-functional theory (DFT) Python code based on the projector-augmented wave (PAW) method and the atomic simulation environment (ASE)
