gcc-env:
    compiler:
        - toolchain: gcc
          spec: gcc@13
    mpi:
        spec: cray-mpich@8.1.30
        gpu: null
    unify: true
    specs:
        - python@3.9.13
        - py-pymatgen@2024.8.9
        - py-cloudpickle
        - py-numpy
        - py-scikit-image
        - py-seekpath
        - py-phonopy@2.25.0
        - py-symfc@1.3.4
        - critic2
    views:
        default:
            link: all
            uenv:
                add_compilers: true
                prefix_paths:
                    LD_LIBRARY_PATH: [lib, lib64]
                    PATH: [bin]
