gcc-env:
    compiler:
        - toolchain: gcc
          spec: gcc@13
    mpi:
        spec: cray-mpich@8.1.30
        gpu: null
    unify: true
    specs:
        - python@3.11
        - py-pydantic
        - py-toml
        - py-numpy
        - py-matplotlib
        - py-ppafm@0.4.0
    views:
        default:
            link: all
            uenv:
                add_compilers: true
